A repo for the project submitted in partial fulfillment of the [Developing Data Products][2] course on [Coursera][1].

## Sumbission info

* Published [App][3] on ShinyApps
* Submitted [Presentation][4] on GitHub
* The Shiny server is in [server.R][5] and the Shiny front-end in [ui.R][6] on GitHub

Additional material provided on [GitHub repo][7]:

* ```Presentation.Rmd```: A plain text version of the slidify presentation
* ```About.Rmd```: R Markdown file that is included in Shiny App (Note here that in order to reproduce the app locally this Markdown file needs to be saved in the same directory as ```ui.R``` and ```server.R```)

## Guidelines to reproduce locally

Guidelines to reproduce this project locally on your PC

To run locally this App on your computer you do NOT need to fork this repo. Please follow these instructions:

1. Install the necessary packages to run RStudio's Shiny Server locally. Please view the well documented requirements in the getting started page: http://shiny.rstudio.com/articles/shinyapps.html

2. Run the following command in RStudio:

```
library(shiny); require(shinyapps); require(rsconnect);
runGitHub("DevDataProd", "Const4nce")
```

## Instructions

* Write a shiny application with associated supporting documentation. The documentation should be thought of as whatever a user will need to get started using your application. 
* Deploy the application on Rstudio's shiny server.
* Share the application link by pasting it into the text box below.
* Share your server.R and ui.R code on github

The application must include the following:

* Some form of input (widget: textbox, radio button, checkbox, ...).
* Some operation on the ui input in sever.R.
* Some reactive output displayed as a result of server calculations.
* You must also include enough documentation so that a novice user could use your application.  
* The documentation should be at the Shiny website itself. Do not post to an external link.

The Shiny application in question is entirely up to you. However, if you're having trouble coming up with ideas, you could start from the simple prediction algorithm done in class and build a new algorithm on one of the R datasets packages. Please make the package simple for the end user, so that they don't need a lot of your prerequisite knowledge to evaluate your application. You should emphasize a simple project given the short time frame.

## Reproducible Pitch Presentation

OK, you've made your shiny app, now it's time to make your pitch. You get 5 slides (inclusive of the title slide) to pitch a your app. You're going to create a web page using Slidify or Rstudio Presenter with an html5 slide deck.

Here's what you need

* 5 slides to pitch our idea done in Slidify or Rstudio Presenter.
* Your presentation pushed to github or Rpubs.
* A link to your github or Rpubs presentation pasted into the text box below

Your presentation must satisfy the following

* It must be done in Slidify or Rstudio Presenter.
* It must be 5 pages.
* It must be hosted on github or Rpubs.
* It must contained some embedded R code that gets run when slidifying the document.

Notice to publish your slidify presentation to github or Rpubs, there's the publish command. This link outlines how to do it (it's one line).

http://slidify.org/publish.html

Rstudio presenter has a button to publish directly to Rpubs https://support.rstudio.com/hc/en-us/articles/200714023-Displaying-and-Distributing-Presentations. If you are using Rpubs, put in the link to the presentation into the submission box as a http:// link not a https:// link.

You can also publish using both formats to github manually using gh-pages, though your github branch must have a .nojekyll fle and be on a branch names gh-pages. There's more on gh-pages here https://pages.github.com/ and there is a video lecture outlining how to do this.

[1]: www.coursera.org
[2]: https://www.coursera.org/learn/data-products
[3]: https://carcheou.shinyapps.io/Amsterdam_Transportation_App/
[4]: Const4nce.github.io/DevDataProd/presentation.html
[5]: https://github.com/Const4nce/DevDataProd/blob/master/server.R
[6]: https://github.com/Const4nce/DevDataProd/blob/master/ui.R
[7]: https://github.com/Const4nce/DevDataProd
